In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
from pathlib import Path

pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)

In [2]:
import sys
print(sys.executable)

/Users/lopty/Documents/quant/momentum-etf-backtest/.venv/bin/python

In [3]:
TICKERS = ["SPY", "EFA", "AGG", "GLD", "DBC", "VNQ", "BIL"]
prices = yf.download(TICKERS, start="2000-01-01", auto_adjust=True)
prices.head()

[*********************100%***********************]  7 of 7 completed

Price      Close                                High          ... Open                Volume                  \
Ticker       AGG BIL DBC EFA GLD        SPY VNQ  AGG BIL DBC  ...  GLD        SPY VNQ    AGG BIL DBC EFA GLD
Date                                                          ...
2000-01-03   NaN NaN NaN NaN NaN  91.367546 NaN  NaN NaN NaN  ...  NaN  93.134430 NaN    NaN NaN NaN NaN NaN
2000-01-04   NaN NaN NaN NaN NaN  87.794472 NaN  NaN NaN NaN  ...  NaN  90.169948 NaN    NaN NaN NaN NaN NaN
2000-01-05   NaN NaN NaN NaN NaN  87.951569 NaN  NaN NaN NaN  ...  NaN  87.912305 NaN    NaN NaN NaN NaN NaN
2000-01-06   NaN NaN NaN NaN NaN  86.538055 NaN  NaN NaN NaN  ...  NaN  87.715978 NaN    NaN NaN NaN NaN NaN
2000-01-07   NaN NaN NaN NaN NaN  91.563828 NaN  NaN NaN NaN  ...  NaN  88.147853 NaN    NaN NaN NaN NaN NaN

Price
Ticker           SPY VNQ
Date
2000-01-03   8164300 NaN
2000-01-04   8089800 NaN
2000-01-05  12177900 NaN
2000-01-06   6227200 NaN
2000-01-07   8066500 NaN

[5 rows x 35 columns]

In [4]:
prices.shape

(6632, 35)

In [5]:
prices.tail()

Price           Close                                                                            High             \
Ticker            AGG        BIL        DBC         EFA         GLD         SPY        VNQ        AGG        BIL
Date
2026-05-11  98.919998  91.480003  31.059999  103.739998  434.649994  739.299988  96.690002  99.110001  91.480003
2026-05-12  98.629997  91.489998  31.690001  103.139999  432.929993  738.179993  96.690002  98.730003  91.489998
2026-05-13  98.669998  91.489998  31.370001  103.830002  430.500000  742.309998  95.889999  98.690002  91.500000
2026-05-14  98.639999  91.510002  31.150000  103.459999  427.209991  748.169983  95.320000  98.889999  91.510002
2026-05-15  98.019997  91.529999  31.190001  101.720001  417.290009  739.169983  93.910004  98.199997  91.540001

Price                  ...        Open                            Volume                                               \
Ticker            DBC  ...         GLD         SPY        VNQ        AGG        BIL        DBC         EFA        GLD
Date                   ...
2026-05-11  31.170000  ...  434.179993  736.450012  96.900002  6848100.0  6150400.0  3213600.0  10717500.0  5569100.0
2026-05-12  31.700001  ...  430.700012  736.890015  96.620003  6336400.0  7332100.0  1301900.0  15770900.0  6660900.0
2026-05-13  31.719999  ...  430.519989  738.469971  96.230003  5396300.0  7467300.0   777700.0   9578900.0  4180300.0
2026-05-14  31.190001  ...  430.299988  743.650024  96.160004  5123900.0  6764000.0   679000.0   8943600.0  4021400.0
2026-05-15  31.240000  ...  417.640015  741.789978  95.099998  8026300.0  9408800.0   832200.0  17916800.0  9335200.0

Price
Ticker           SPY        VNQ
Date
2026-05-11  44024000  3868500.0
2026-05-12  54185300  2325100.0
2026-05-13  44200200  5047300.0
2026-05-14  45307600  2521700.0
2026-05-15  60290000  4533200.0

[5 rows x 35 columns]

In [6]:
prices["Close"].apply(lambda col: col.first_valid_index())

Ticker
AGG   2003-09-29
BIL   2007-05-30
DBC   2006-02-06
EFA   2001-08-27
GLD   2004-11-18
SPY   2000-01-03
VNQ   2004-09-29
dtype: datetime64[s]

In [7]:
prices = prices["Close"]
prices.head()

Ticker      AGG  BIL  DBC  EFA  GLD        SPY  VNQ
Date
2000-01-03  NaN  NaN  NaN  NaN  NaN  91.367546  NaN
2000-01-04  NaN  NaN  NaN  NaN  NaN  87.794472  NaN
2000-01-05  NaN  NaN  NaN  NaN  NaN  87.951569  NaN
2000-01-06  NaN  NaN  NaN  NaN  NaN  86.538055  NaN
2000-01-07  NaN  NaN  NaN  NaN  NaN  91.563828  NaN

In [9]:
prices.shape
prices.columns
prices.tail()

Ticker            AGG        BIL        DBC         EFA         GLD         SPY        VNQ
Date
2026-05-11  98.919998  91.480003  31.059999  103.739998  434.649994  739.299988  96.690002
2026-05-12  98.629997  91.489998  31.690001  103.139999  432.929993  738.179993  96.690002
2026-05-13  98.669998  91.489998  31.370001  103.830002  430.500000  742.309998  95.889999
2026-05-14  98.639999  91.510002  31.150000  103.459999  427.209991  748.169983  95.320000
2026-05-15  98.019997  91.529999  31.190001  101.720001  417.290009  739.169983  93.910004

In [10]:
prices.shape

(6632, 7)

In [11]:
prices.notna().idxmax()

Ticker
AGG   2003-09-29
BIL   2007-05-30
DBC   2006-02-06
EFA   2001-08-27
GLD   2004-11-18
SPY   2000-01-03
VNQ   2004-09-29
dtype: datetime64[s]

In [13]:
for ticker in prices.columns:
    first_valid = prices[ticker].first_valid_index()
    series_after_start = prices[ticker].loc[first_valid:]
    nan_count = series_after_start.isna().sum()
    print(f"{ticker}: {nan_count} missing days after {first_valid.date()}")

AGG: 0 missing days after 2003-09-29
BIL: 0 missing days after 2007-05-30
DBC: 0 missing days after 2006-02-06
EFA: 0 missing days after 2001-08-27
GLD: 0 missing days after 2004-11-18
SPY: 0 missing days after 2000-01-03
VNQ: 0 missing days after 2004-09-29

In [14]:
# Make sure the output directory exists
output_dir = Path("../data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

# Save to Parquet
output_path = output_dir / "prices.parquet"
prices.to_parquet(output_path)

print(f"Saved {prices.shape[0]} rows × {prices.shape[1]} columns to {output_path}")

Saved 6632 rows × 7 columns to ../data/processed/prices.parquet

In [15]:
prices_check = pd.read_parquet(output_path)
print(f"Loaded {prices_check.shape[0]} rows × {prices_check.shape[1]} columns")
print(f"Matches original: {prices.equals(prices_check)}")

Loaded 6632 rows × 7 columns
Matches original: True

In [16]:
import sys
sys.path.insert(0, "..")

from src.data_loader import load_prices

prices = load_prices()
print(prices.shape)
prices.tail()

(6632, 7)

Ticker            AGG        BIL        DBC         EFA         GLD         SPY        VNQ
Date
2026-05-11  98.919998  91.480003  31.059999  103.739998  434.649994  739.299988  96.690002
2026-05-12  98.629997  91.489998  31.690001  103.139999  432.929993  738.179993  96.690002
2026-05-13  98.669998  91.489998  31.370001  103.830002  430.500000  742.309998  95.889999
2026-05-14  98.639999  91.510002  31.150000  103.459999  427.209991  748.169983  95.320000
2026-05-15  98.019997  91.529999  31.190001  101.720001  417.290009  739.169983  93.910004